
# Main Config
# -----------------------

# Site Info
url: http://kevinthompson.info
title: Kevin Thompson
subtitle: Mild-mannered developer by day, caffeine-fueled autodidact by night.
author: Kevin Thompson

# Contact Information
skype: thompson.kevind
email: kevin@kevinthompson.info
phone: (760) 525-4041

# Date Format (Default: "ordinal" = "July 22nd 2007")
date_format: "ordinal"

# RSS
subscribe_rss: /feed/index.xml

# Github 
github_user: "kevinthompson"
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: true

# Jekyll & Plugins
# -----------------------

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:categories/:title
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides: