
# ------------------------------
# Jekyll Configuration
# ------------------------------
auto: false
markdown: rdiscount
permalink: /:categories/:title/
pygments: true
rdiscount:
  extensions: [smart]
  
# ------------------------------
# Custom Variables
# ------------------------------
skype: thompson.kevind
phone: (760) 525-4041
email: kevin@kevinthompson.info